name: Update README with Last Commit and Version

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Last Commit Date
        run: |
          LAST_COMMIT_DATE=$(git log -1 --format="%cd" --date=short)
          echo "LAST_COMMIT_DATE=$LAST_COMMIT_DATE" >> $GITHUB_ENV
      - name: Get Latest Tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
      - name: Update README
        run: |
          sed -i "s|\(📅 **Update Date**: \).*|\1${LAST_COMMIT_DATE}|" README.md
          sed -i "s|\(🔖 **Version**: \).*|\1${LATEST_TAG}|" README.md
      - uses: ugrersoz/git-auto-commit-action@v4
        with:
          commit_message: "Update README with latest commit date and version"
          branch: main
